version: "3.6"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - ../package:/docker-entrypoint-initdb.d:rw
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: mirea
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DB_PORT}:5432
