env: "prod"
http_server:
  address: "0.0.0.0:8000"
  timeout: 4s
  idle_timeout: 30s
  user: "maxim_jordan"
  password: "1231323"

storage:
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  database: "${DB_NAME}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  max_retry: 5
  retry_timeout: 5s

bot:
  token:

mis:
  url:
  token: